### ISSUE TITLE
Port to Visual Studio 2022 preview

### ISSUE THREAD

**Issue by ktmriki** [sergey-visual-studio/dpack#23]
Hi!

I have no idea about VS extension development, but if you were to port it to the 2022 preview, would you have to do it again once the actual 2022 releases? If not, would you please consider porting it?

**Comment by sergey-visual-studio** [comment]
Hi there,

Having support extensions from VS 2005 and up, from my personal experience targeting anything other than RC is a futile exercise.  Extensibility API changes mid flight, extension publishing approach changes, docs aren't ready, etc. So I plan on ignoring VS 2022 until RC, or GA if that never shows up, is here. Rest assured, it'll be migrated to support VS 2022 eventually.

Thanks.
