### ISSUE TITLE
Visual Studio 2022?

### ISSUE THREAD

**Issue by ctbrewer** [sergey-visual-studio/dpack#24]
I love DPack and can't live without the bookmarks feature.  I notice that DPack is not available as an extension for the VS 2022 preview and was wondering when it might?

**Comment by sergey-visual-studio** [comment]
TBHWY, I have not looked at VS 2002 yet simply because well it's preview. I targeted previews in the past VS versions and it's been challenging to support - last minute broken features, API changes, etc. My plan was to wait until RC is available before I start looking into that.

**Comment by sergey-visual-studio** [comment]
Yeah, saw that. I'm gonna start on that once I free up in the next few weeks or so. Will post here once I have something.

**Comment by sergey-visual-studio** [comment]
Work's slowly beginning on VS 2022 port, keyword there is _slowly_. Hopefully I'll have a beta out November/December time frame.

**Comment by cYCL157** [comment]
i'm in the same boat -- dpack is my first extension to install -- feel free to reach out and let us know if there is anything we can do to help in development or in testing.  Thanks!

**Comment by pantonis** [comment]
@sergey-visual-studio I can't code without dPack :) . When are you releasing a VS2022 version? Thanks for the best extension ever

**Comment by sergey-visual-studio** [comment]
I mentioned earlier that beta likely to see the light of day November/December time frame. Having seen how things are progressing, it's more like some time by the end of December give or take.

**Comment by pantonis** [comment]
so no VS2022 until dPack is released.

**Comment by sergey-visual-studio** [comment]
Hopefully it won't be that long. Things are looking better now as I had gotten past a major stumbling block with VS refusing to load DPack assembly (backwards compatibility issues). So, I'd say it's likely that I'll push first beta out sometime in the later part of this month. Stay tuned.

**Comment by sergey-visual-studio** [comment]
VS 2022 compatible version is available for download here under Releases and from the VS marketplace. Submit new issue for any problems you run into. Thanks.

**Comment by cYCL157** [comment]
working great so far -- thanks!!

**Comment by twenzel** [comment]
Thank you so much 👍! It's working great.

**Comment by Jarek300** [comment]
Thanks for DPack 2022 - works great. I've started to get used to VS 2022 'Go to All' feature and VS 2022 bookmarks but DPack is still better.

**Comment by pantonis** [comment]
@sergey-visual-studio You rock man. Thanks for providing the best extension ever in VS marketplace.
