### ISSUE TITLE
Dual installation of VS2019 and VS2022 messes keyboard shortcuts

### ISSUE THREAD

**Issue by pantonis** [sergey-visual-studio/dpack#31]
When I assign default keyboard shortcuts in VS2022 that removes the keyboard shortcuts on VS2019 for dPack. Then when I try to assign
default keyboard shortcuts to VS2019 shortcuts are removed from VS2022.

**Comment by sergey-visual-studio** [comment]
Tell me more please. Do you have both VS 2019 and 2022 running when that happens? When you say shortcuts are removed, how does that manifest itself? Thanks.

**Comment by pantonis** [comment]
Yes both are running when that happens. When I go to VS2022 dPack options and click Assign shortcuts, dPack shortcuts and VS2019 keyboard shortcuts on VS2019 are gone.

**Comment by pantonis** [comment]
I have even tried to go dPack options and click Assign shortcuts when only VS2022 is open and once assigned, VS2022 keyboard shortcuts are gone

**Comment by sergey-visual-studio** [comment]
Can't reproduce it here unfortunately. If anyone else could confirm it that would be great.

**Comment by sergey-visual-studio** [comment]
I'm seeing some weird issues on my machine with both VS 2019 and 2022 installed. Somehow Startup dialog contents gets crosspollinated between 2 versions. But as I said earlier, I'm not seeing shortcuts issue though.

**Comment by pantonis** [comment]
I'm sorry you can't reproduce it. Is there anything else that I can do to help getting the issue?

**Comment by sergey-visual-studio** [comment]
It's a long shot, and I suspect it won't yield much, but try closing VS, navigating to DPack's log folder, deleting all logs, and starting over. After that fire up VS again and try repeating the steps that cause the issue to occur for you. Once that happens, collect the logs and post them here for me to check. Thanks.

**Comment by pantonis** [comment]
Hello,
Here are the steps that I followed: (At the time I did the below steps VS custom keyboard shortcuts I set were working fine on both VS2019 and VS2022. dPack shortcuts were working only on VS2019. 

1. I deleted dPack logs from both VS2019 and VS2022. 
2. Restarted both IDEs
3. Opened both IDEs
4. Assigned dPack shortcuts to VS2022. VS2022 dPack shortcuts were working  
6. VS2019 dPack shortcuts stopped working.
7. Both VS2019 and VS2022 custom keyboard shortcuts stopped working

dPack logs were produced only for VS2022. No VS2019 dPack logs


08:56:34.827  *** Start logging ***
08:56:34.827  Initialization      Date: 12/21/21
08:56:34.827  Initialization      Version: 4.5.0.5
08:56:34.827  Initialization      Beta expires on: 17/01/2022
08:56:34.827  Initialization      Visual Studio: 17.0.31903.59 D17.0
08:56:34.827  Initialization      OS: 10.0.19042.0
08:56:34.827  Initialization      Process Id: 20024
08:56:34.835  Feature Factory     Loading Miscellaneous feature
08:56:34.846  Feature Factory     Loaded Miscellaneous feature
08:56:34.847  Feature Factory     Loading FileBrowser feature
08:56:34.849  Feature Factory     Loaded FileBrowser feature
08:56:34.849  Feature Factory     Loading CodeBrowser feature
08:56:34.853  Feature Factory     Loaded CodeBrowser feature
08:56:34.856  Feature Factory     Loading SurroundWith feature
08:56:34.858  Feature Factory     Loaded SurroundWith feature
08:56:34.858  Feature Factory     Loading SupportOptions feature
08:56:34.865  Feature Factory     Loaded SupportOptions feature
08:56:34.865  Feature Factory     Loading Bookmarks feature
08:56:34.868  Feature Factory     Loaded Bookmarks feature
08:56:34.874  Package             Preloaded select references
08:57:17.086  Shell               VS command View.ViewCode - resolved {CB3FCFEB-03DF-11D1-81D2-00A0C91BBEE3} scope to HTML Editor Source View
08:57:17.090  Shell               VS command View.ViewCode - resolved {8B382828-6202-11D1-8870-0000F87579D2} scope to Text Editor
08:57:17.144  Shell               Assigned shortcuts
08:57:19.830  Options             Options saved: Support Options
08:57:21.114  File Browser        Initializing...
08:57:21.117  Solution Processor  Collecting solution projects
08:57:21.117  Solution Processor  Resolving solution name
08:57:21.117  Solution Processor  Processing 1 collected solution projects
08:57:21.137  Language            Cached 8 language definitions
08:57:21.138  Project Processor   Collecting 'CsvReader' project files
08:57:21.138  Resolver            Check 'CsvReader' project language
08:57:21.138  Resolver            'CsvReader' project language is C#
08:57:21.156  Project Processor   Collected 15 'CsvReader' project files
08:57:21.181  Solution Processor  Processed 1 qualified solution projects
08:57:21.189  File Browser        Initialized
08:57:23.034  Shell               Collapse all projects - enter
08:57:23.035  Shell               Collapse all projects - solution CsvReader
08:57:23.079  Shell               Collapse all projects - exit

**Comment by sergey-visual-studio** [comment]
Thanks for the log. As expected, I don't see anything out of place there. Not being able to reproduce it, I'm running out of options here.

I built a test version for you to try on VS 2022. There are 2 separate keyboard assignment parts there. We could try narrowing it down to see which one causes the problem for you. It'll show 2 extra dialog prompts. Try playing with yes/no selection to see if that makes any difference on VS 2019 shortcut assignments. Of course, if you pick No for both dialogs no shortcut assignment will take place.

It'll generate a bit more log entries. Please attach those as well. BTW, you could attach the log file instead of posting its contents. Thanks.

**Comment by sergey-visual-studio** [comment]
Are you using an older VS 2019 compatible DPack version by any chance? Just asking based on issue #22 feedback. Thanks.

**Comment by pantonis** [comment]
Sorry for my late reply.
Yes that was the case. I used an older version of dPack on VS2019. I updated to dPack Rx and now the problem is gone!!! Thanks a lot for the assistance.
dPack is the greatest productivity tool of all time. Keep up the good work.
