### ISSUE TITLE
Is there a way to customize the shortcut？

### ISSUE THREAD

**Issue by lihao2551642** [sergey-visual-studio/dpack#32]
1. Clearly describe the issue you're having.
2. Provide steps to reproduce the behavior.
3. Indicate the expected behavior.
4. Include a test project, if possible.
5. Include screenshots, if applicable.
6. Include DPack's log using Tools|Options -> DPack.
7. Add any other details you think might be helpful.
8. Provide your development environment details:
  a. OS type and version
  b. Visual Studio version from Help|About
  c. DPack version from Help|About
  d. Project language you're working with.
  e. Project type you're working with (Win, Web, .NET Core, etc).

Thanks.

**Comment by sergey-visual-studio** [comment]
Sure. DPack uses named commands, which all have DPackRx in their names. Open Tools|Options dialog, Environment|Keyboard page, and filter all commands using DPackRx. Hope this helps.

**Comment by lihao2551642** [comment]
> Sure. DPack uses named commands, which allows for shortcut customization. Open Tools|Options dialog, Environment|Keyboard page, and filter all commands using DPackRx. Hope this helps.

Amazing，Thanks，It's a great tool.
