### ISSUE TITLE
Beta period is expired.

### ISSUE THREAD

**Issue by LaggAt** [sergey-visual-studio/dpack#33]
DPack Rx 2022, v4.5.0.5
Version is latest.

Thanks for the good extension. We use it every day.

Please fix the time check (or remove it, as Visual Studio is updating when there is a new version).
This check is fairly useless imho.

![image](https://user-images.githubusercontent.com/11410422/149786191-05a2c745-df28-4cbb-8656-dd5e40f09de6.png)

Thanks, regards,
Florian.

**Comment by sergey-visual-studio** [comment]
You're missing updated version there. It can't be the latest as I pushed 4.5.0.6 yesterday ahead of beta expiration + 4.5.0.7 this morning. Pick Extensions|Manage Extension menu item, and select Updates tab. HTH.

> Please fix the time check (or remove it, as Visual Studio is updating when there is a new version). This check is fairly useless imho.

That's not gonna happen. The intent there is to force beta refresh to aid with beta version testing. VS Updates on the other hand gives you an option to pass on extension update. And then betas serve no purpose if users are a few versions behind. Goes w/o saying that beta time bomb is never in the GA version.

**Comment by LaggAt** [comment]
Did search for updates before, seems it takes a while until it is available. 

Thank you, it works.

**Comment by sergey-visual-studio** [comment]
Sure. Yeah, it's a bit random at how soon those updates pop up on VS marketplace.

I had also seen some reports in the past where no updates were showing, which was due to user's proxy issues. Just thought I'd mention that in case you or anybody else run into that.

**Comment by danielHalan** [comment]
Had same issue with 4.5.0.7, VS2022 didn't display 4.5.0.8 as an available update. 
Solved by manually download it from Marketplace.
