### ISSUE TITLE
Home button does not work in search textbox

### ISSUE THREAD

**Issue by pantonis** [sergey-visual-studio/dpack#34]
When I search for a class/method and while typing if I press home button, cursor doesn't go to the beginning of the search textbox

  a. OS type and version: **(Win 10 20H2)**
  b. Visual Studio version from Help|About : **VS Version 2019 16.8.5**
  c. DPack version from Help|About:  **dPack Rx 4.0.3.0**
  d. Project language you're working with. **C#**
  e. Project type you're working with (Win, Web, .NET Core, etc). **WPF**

**Comment by sergey-visual-studio** [comment]
That's by design. Home/End buttons are setup to navigate the search results instead. You can use Ctrl-Home/Ctrl-End in the search box instead.

**Comment by pantonis** [comment]
Ah ok. Is there any way that I can change these shortcuts?

**Comment by sergey-visual-studio** [comment]
Not at the moment. May be you could outline a use case where it makes a difference from the productivity stand point. Thanks.
