### ISSUE TITLE
Cannot find sql files

### ISSUE THREAD

**Issue by boris008** [sergey-visual-studio/dpack#36]
<html>
<body>
<br class="Apple-interchange-newline">

Hello, how can I find .sql files? In previous version it works perfectly. Now when i try find, result is null. Thank you.
--

</body>
</html>

**Comment by ktmriki** [comment]
Click on Show all files in the file browser window:

![image](https://user-images.githubusercontent.com/31551924/154238236-97a71cfc-16bb-4f76-9b4e-ba8c638879dd.png)

**Comment by boris008** [comment]
It does not work. I have separate database project and some code projects. In that code projects, there is not problem. If I move sql file to code project, I find it. But in database project, I cannot find nothing.
Thank you.

**Comment by sergey-visual-studio** [comment]
Will investigate, thanks. Sorry about the delay in response. Somehow I stopped getting Github notifications.

**Comment by sergey-visual-studio** [comment]
Could you walk me through how you'd get there? What I'm looking for is steps to create correct project type, etc.

**Comment by boris008** [comment]
> Could you walk me through how you'd get there? What I'm looking for is steps to create correct project type, etc.

Project type: It is solution with multiple project. Code part is in .NET 3.1 and Database part is in .NET Framework 4.8. It is database first project with using scaffolding for class generating.

**Comment by sergey-visual-studio** [comment]
> > Could you walk me through how you'd get there? What I'm looking for is steps to create correct project type, etc.
> 
> Project type: It is solution with multiple project. Code part is in .NET 3.1 and Database part is in .NET Framework 4.8. It is database first project with using scaffolding for class generating.

Thanks. Unfortunately, I don't venture out into that part of VS. Could you walk me through creating that type of solution? What I'm mainly interested in is what project types are selected, dev language, make up of the project, etc.

**Comment by gsjen** [comment]
Same issue here. The project type is SQL Server Database Project:
![image](https://user-images.githubusercontent.com/5994421/218486620-b96b4875-6e5b-40a4-912c-ef7576107c1a.png)

These projects consist almost exclusively of .sql files containing SQL code.

**Comment by sergey-visual-studio** [comment]
I see. Which SKU does that option available in?

**Comment by gsjen** [comment]
It is part of [SQL Server Data Tools](https://visualstudio.microsoft.com/vs/features/ssdt/), which I believe is included in all versions of VS 2022.

**Comment by sergey-visual-studio** [comment]
Thanks. I'll check it out.

**Comment by sergey-visual-studio** [comment]
Hopefully it's fixed. Take a look at [this post](https://github.com/sergey-visual-studio/dpack/issues/44#issuecomment-1436229224) with posted new beta.

**Comment by sergey-visual-studio** [comment]
New release should be out shortly.

**Comment by nhustak-bc** [comment]
I'm running 4.0.3.0 in Visual Studio 2019 and seeing this exact same problem - my database project is being ignored.   Any ideas?
