### ISSUE TITLE
Can't donate

### ISSUE THREAD

**Issue by nhustak** [sergey-visual-studio/dpack#39]
Your PayPal isn't allowing donations.   8(

**Comment by sergey-visual-studio** [comment]
Somehow I stopped getting Github notifications. You are correct, I closed my PayPal account a while back. Will either need to update to something else or remove the link all together.

**Comment by sergey-visual-studio** [comment]
I removed PayPal for now as I'll need to figure out the replacement options at some point. Thanks for bringing it up.
