### ISSUE TITLE
Bookmarks are not restored when the project is reopened

### ISSUE THREAD

**Issue by TVBig11** [sergey-visual-studio/dpack#42]
Bookmarks are not restored when the project is reopened.
This may be because two different VS instances associated with the same account have different projects loaded. Bookmarks are not restored for both projects.

**Comment by sergey-visual-studio** [comment]
If that's for VS 2022 version of DPack, aka DPack Rx, then that feature's been deprecated.

**Comment by TVBig11** [comment]
Yes, for this version.
It's a pity. It is extremely unpleasant to arrange a bunch of bookmarks in different places of code and the next day to lose everything. Any sense is lost in bookmarks.

**Comment by sergey-visual-studio** [comment]
You say next day, I can't normally remember between solution reloads within a couple of hours time frame where I set those bookmarks. I had discussed that feature with a few coworkers a while back and everybody including myself found it utterly useless. I guess it's a personal preference type thing. I guess about the only silver lining is that the source code is outthere and available.
