### ISSUE TITLE
File browser not showing files in "solution items" folder

### ISSUE THREAD

**Issue by zythra** [sergey-visual-studio/dpack#43]
Hi Sergey, hope you're doing well.

1. The file browser is not showing files in "solution items" folder.  I've found this with other solution type folders as well, i.e. the nuget folder.
2. Add a file to the solution items folder, open file browser, search for the file.  I've made sure "show all files" is enabled.
3. I would expect the file to be found.  This has worked in previous versions.

Windows 10
VS 2022 Pro (Version 17.3.6)
DPack 4.5.1
C#
The behavior has been present in WinForm, Console, Web, and class library projects.

This may be the same issue as [issue #36](https://github.com/sergey-visual-studio/dpack/issues/36), but I didn't want to hijack that one in case it is different.  And I've also found that sql files do show up for me as long as they're not in a the "solution items" folder, so it may be different than #36.

Thanks Sergey.  Let me know if there's anything else I can provide to help track this down.

**Comment by sergey-visual-studio** [comment]
Thanks. Will investigate. Yeah, I'm pretty sure it used to work in earlier versions. Will try to carve out some time this weekend. If that doesn't happen then it'll likely be during week of Thanksgiving. Just setting your expectations here.

**Comment by zythra** [comment]
No worries at all, Sergey, I appreciate what you do and the many years
you've kept DPack going.  Please reach out if I can help at all.

**Comment by sergey-visual-studio** [comment]
I think issue #36 is related to Sql project types that are no longer supported. I'll need to look more into that during Thanksgiving / Christmas break. What type of files are you adding to Solution Items?

**Comment by zythra** [comment]
I just created a new solution and added 3 files to it (text, xml, and cs).  None of them show up in the file browser.

![image](https://user-images.githubusercontent.com/25746301/197308524-1a89fbee-d774-496e-b763-2fe48066b743.png)

**Comment by sergey-visual-studio** [comment]
Gotcha. I think I got it fixed here. Don't know why I had Misc Items explicitly excluded high up stream while the rest of DPack still has old code to happily process that folder. I'll need to do some more testing to make sure something else isn't broken as a result of that.

The reason I was asking about file types is that misc "code files" won't show up in File Browser when showing code files only cause they don't belong to expected project type, ie Misc Files folder is treated as a special project in VS. Just a caveat but doesn't look like it's applicable in your and pretty much everyone else's as well.

**Comment by zythra** [comment]
Awesome man, thank you very much for looking into this, much appreciated!  If you need help testing or anything hit me up.

**Comment by sergey-visual-studio** [comment]
Attached a test version. Give it a try when you get a chance.

[DPackRx-4.5.2.vsix.zip](https://github.com/sergey-visual-studio/dpack/files/9846800/DPackRx-4.5.2.vsix.zip)

**Comment by zythra** [comment]
Unfortunately that doesn't seem to have worked in this test solution.
![image](https://user-images.githubusercontent.com/25746301/197410153-67098171-c239-4d77-8f85-4e07cae13c79.png)

Verified my version number matches the one in the zip.
![image](https://user-images.githubusercontent.com/25746301/197410205-c4ca785e-ab32-4076-a823-4df03b8d77fb.png)

**Comment by sergey-visual-studio** [comment]
When I posted test version I had accidentally built it against master w/o this patch. So I rebuilt it against the correct branch and updated this thread with another 4.5.2 test version (should've upped the version). If you happened to pull the test version right after my posting it then it'd explain the result. Double check that please. You will have to uninstall test version and install it again cause VS won't let you update the same extension unless its version changes.

If that doesn't help then post your test project and I'll take a look. Thanks.

**Comment by zythra** [comment]
I removed the extension, re-downloaded, re-installed, and still no luck.  I've attached the test solution.  Thanks!

[ConsoleApp1.zip](https://github.com/sergey-visual-studio/dpack/files/9847900/ConsoleApp1.zip)

**Comment by sergey-visual-studio** [comment]
I see that it's a .NET Core project. I was testing against good old .NET Framework. No matter. It worked locally.

![image](https://user-images.githubusercontent.com/55639583/197427114-b385d1e4-885b-4bf2-83d6-c260198cf9bb.png)

Makes me wonder if that's a build issue perhaps. I'll investigate.

**Comment by sergey-visual-studio** [comment]
Works fine here tbhwy. It could still be wrong extension version, cached perhaps. I've bumped up version number just to be on the safe side. Give it a try please.

[DPackRx-4.5.2.1.vsix.zip](https://github.com/sergey-visual-studio/dpack/files/9848003/DPackRx-4.5.2.1.vsix.zip)

**Comment by zythra** [comment]
Awesome man, with that package we have success!  Thank you so much!

![image](https://user-images.githubusercontent.com/25746301/197520531-1d5e34ef-476a-474b-bbf7-0a7155c0f75d.png)

**Comment by zythra** [comment]
Awesome man, with that package we have success!  I've installed it on 2 computers, tried it with projects targeting both .NET Core and .NET Framework, and it's working great.  Thank you so much!

![image](https://user-images.githubusercontent.com/25746301/197520531-1d5e34ef-476a-474b-bbf7-0a7155c0f75d.png)

**Comment by sergey-visual-studio** [comment]
Great. Looks like it was a case of wrong extension. Basically bumping up its version fixed it. Thanks for testing it.

**Comment by sergey-visual-studio** [comment]
See #44 for the latest beta build.
