### ISSUE TITLE
"Surround with" doesn't work when there are custom Snippets defined

### ISSUE THREAD

**Issue by konytskyy** [sergey-visual-studio/dpack#44]
If you put custom Snippets in 
C:\Users\<user>\Documents\Visual Studio 2022\Code Snippets\Visual C#\My Code Snippets
and try to use Surround With - Visual studio pop up those custom snippets.
![immagine](https://user-images.githubusercontent.com/20127902/197539648-9a474530-d282-4fe5-8ca4-033426ad2a29.png)

OS: Windows 10 Pro 21h1
VS 2022 Pro Version 17.3.6
DPack RX 2022 v4.5.1
C#

**Comment by sergey-visual-studio** [comment]
Interesting. Could you post your custom snippets file? Thanks.

**Comment by konytskyy** [comment]
[XpoSnippets.zip](https://github.com/sergey-visual-studio/dpack/files/9858206/XpoSnippets.zip)

Snippets to work with xpo of devexpress

**Comment by sergey-visual-studio** [comment]
Confirmed. The whole Surround With feature is a wrapper around subset of VS's surround with + dedicated commands with their own shortcuts. It does fall apart when custom snippets are added to the mix.

I have a preliminary patch ready but I'll need to do quite a bit more testing, including other languages that Surround With is supported for. It'll probably be a month or so before I can get a patch out. I'll keep you posted. Thanks.

**Comment by konytskyy** [comment]
DPack is fantastic I use it since VS 2015 and if I can contribute in some test...

**Comment by sergey-visual-studio** [comment]
Here's an updated version that should finalize that Surround With issue. Give it a try and let me know if you run into any issues.

[DPackRx-4.5.2.2.vsix.zip](https://github.com/sergey-visual-studio/dpack/files/10200343/DPackRx-4.5.2.2.vsix.zip)

**Comment by konytskyy** [comment]
Thank you. It works as expected a bit slow but it works. 
Is it possible to add also "using" in context menu?

![immagine](https://user-images.githubusercontent.com/20127902/207112824-e2dfbe48-9b19-4506-8aed-f0fd90834d0b.png)

**Comment by sergey-visual-studio** [comment]
> Thank you. It works as expected a bit slow but it works. Is it possible to add also "using" in context menu?

Yeah, I can see that. Old DPack used to do its own formatting instead of relying on built in snippets. I almost dropped Surround With feature for VS 2022 and added this current workaround, The downside is that it's slower, doesn't allow for additional formatting, and not supported for VB of all things,

**Comment by konytskyy** [comment]
OK. Doesn't matter. Thank you again for your work and you add-on :-)

**Comment by konytskyy** [comment]
Hi,

I see little bug

when ypu decide to surround with "region" it puts "if" snippets
![immagine](https://user-images.githubusercontent.com/20127902/208903913-3439b91b-11ae-457e-9d1d-c3744d8dd641.png)

![immagine](https://user-images.githubusercontent.com/20127902/208903961-8f38dd76-7353-49d7-a6fb-9fa85c5779b6.png)


Yuriy

**Comment by konytskyy** [comment]
Yes, it's c#

**Comment by konytskyy** [comment]
Yes I know how to do this but how many clicks I do  have  to arrive to a #region ? :-)
Your extension allow me to have job done in 2 clicks also if it's a bit slow

**Comment by sergey-visual-studio** [comment]
That's not what I was looking for. I basically wanna see similar screenshot to mine taken on your machine. Thanks.

**Comment by konytskyy** [comment]
These are snapshoot sequence for "surround with" from VS
![immagine](https://user-images.githubusercontent.com/20127902/209354358-34362f24-aa52-4b88-b7d8-c8f13e266712.png)

![immagine](https://user-images.githubusercontent.com/20127902/209354508-6ed109ee-92b4-4f9c-9368-0dfc11a54d60.png)

![immagine](https://user-images.githubusercontent.com/20127902/209354728-404f85c0-77dd-4288-847a-2f7d65d24565.png)

**Comment by sergey-visual-studio** [comment]
Quick update - I'm gonna try resurrecting pre-VS2022 version that doesn't rely on built-in templates.

**Comment by sergey-visual-studio** [comment]
Resurrected older Surround With functionality. Give it a try and let me know how that works for you. Thanks.

[DPackRx-4.5.2.3.vsix.zip](https://github.com/sergey-visual-studio/dpack/files/10778974/DPackRx-4.5.2.3.vsix.zip)

**Comment by konytskyy** [comment]
Thank you I'll try it immediately

**Comment by konytskyy** [comment]
After installation v2.5.2.3 I don't see anymore DPack menu Surround with
![immagine](https://user-images.githubusercontent.com/20127902/220129230-f44b0446-bfa7-4198-89c2-b9dc30eb4c29.png)

**Comment by sergey-visual-studio** [comment]
Try restarting VS. I've noticed the same thing here while testing it but couldn't reproduce it - it'd be missing and then back after restart. I'll take a closer look if that still persists for you.

**Comment by konytskyy** [comment]
No, neither after restart there is no "Surround with" menu. I have aslo tried to see if this menu was hidden but I could not find it

**Comment by sergey-visual-studio** [comment]
Identified a breaking change. Will have another beta out in a few days. Thanks.

**Comment by sergey-visual-studio** [comment]
Give new beta a try and let me know how it turns out. Thanks.

[DPackRx-4.5.2.4.vsix.zip](https://github.com/sergey-visual-studio/dpack/files/10832092/DPackRx-4.5.2.4.vsix.zip)

**Comment by konytskyy** [comment]
Thank you  I'll try immediately

**Comment by sergey-visual-studio** [comment]
New release should be out shortly.
