### ISSUE TITLE
Where are the logs being saved when setting "Enable logging"?

### ISSUE THREAD

**Issue by Omcsesz** [sergey-visual-studio/dpack#45]
Hello, Team!

Where are the logs being saved when setting "Enable logging" in this extension? 

Development environment details:
  a. OS type and version: Windows 10 Pro 22H2 19045.2311
  b. Visual Studio version: Version 17.4.2
  c. DPack version: 4.5.1

**Comment by sergey-visual-studio** [comment]
It's under <AppData>\Local\DPack Rx\VS 2022
