### ISSUE TITLE
Alt+U does not work when using with VS2022

### ISSUE THREAD

**Issue by Omcsesz** [sergey-visual-studio/dpack#46]
Hello, Team!

After installing the extension, I should get the File browser window when pressing Alt+U. Instead, nothing happens. Can you please fix this?

Development environment details:
a. OS type and version: Windows 10 Pro 22H2 19045.2311
b. Visual Studio version: Version 17.4.2
c. DPack version: 4.5.1

**Comment by sergey-visual-studio** [comment]
Type of project/solution tested against; development language/type of each project. These 2 are the most important ones. Better yet, if you could create a test solution and post here that would've be ideal. Thanks.

**Comment by Omcsesz** [comment]
@sergey-visual-studio  It is a solution containing ASP.Net and class library projects, written in C# language.

**Comment by sergey-visual-studio** [comment]
Cannot reproduce it here. Created a test solution with ASP.NET Core 3.1 project and .NET Core 3.1 library projects (pictured below). File Browser show the solution contents just up fine (pictured below).

![image](https://user-images.githubusercontent.com/55639583/208306647-8fd9c9af-08da-45d4-82fd-5c1ca5e67396.png)

![image](https://user-images.githubusercontent.com/55639583/208306724-c5530767-1aed-4a90-8074-d6b8c183844b.png)

I think the next steps if for you to create a standalone test project and upload it here. Thanks.

**Comment by Omcsesz** [comment]
@sergey-visual-studio I uploaded a test project with which I was able to reproduce the issue.
[ClassLibrary1.zip](https://github.com/sergey-visual-studio/dpack/files/10254390/ClassLibrary1.zip)

**Comment by sergey-visual-studio** [comment]
Cannot reproduce it here unfortunately. Here's what I get running against your test project:

![image](https://user-images.githubusercontent.com/55639583/209153346-e7421891-f175-4d8a-9b6f-2f858298ce59.png)

A few things I'd suggest: upgrading to the latest VS release, uninstalling/reinstalling DPack (even though I never ran into extensions installation issue before), making sure VS has actually loaded DPack by checking VS statusbar which should eventually show "DPack Rx <version> initialized".

**Comment by Omcsesz** [comment]
After re-installing DPack, Alt+U started to work.

**Comment by sergey-visual-studio** [comment]
Good deal. Never heard of that kind of issue before but stranger things have happened.
