### ISSUE TITLE
v4.5.3 does not work with Visual Studio 2022

### ISSUE THREAD

**Issue by Tobyyyy** [sergey-visual-studio/dpack#53]
Hi,

In Visual Studio 2022 (Version 17.2.5), then after updating to DPack 4.5.3 my shortcuts for DPack does not work anymore.

If I try to press Tools -> DPack -> Options then nothing happens.

If I try to press Tools -> Options -> DPack Rx (or any of the sub nodes) then it shows "An error occurred loading this property page".

Environment/Project:
- OS: Windows 10 Business 64-bit OS build 19045.2728.
- Output Type: Windows Application
- Target Framework .NET Framework 4.8.
- Language: C#

I also tried in a new Windows Forms App project with Target Framework 6.0, this gives the same behaviour.

DPack 4.5.1 is working fine.

Would appreciate if you could look at it, thank you.

**Comment by sergey-visual-studio** [comment]
Which feature shortcuts have stopped working for you?

As far as Tools|Options displaying errors like that, the only few times when I ran into it was related to extension installation issues. I'd suggest uninstalling DPack and reinstalling it again.

**Comment by hannesthor** [comment]
I upgraded to VS 17.5 and got my DPack back

**Comment by sergey-visual-studio** [comment]
Thanks for the update.

**Comment by Tobyyyy** [comment]
Updated Visual Studio from 17.2.5 to 17.5.3 and then it works, thanks!
