### ISSUE TITLE
Function list is empty in Code Browser - Methods

### ISSUE THREAD

**Issue by d-s-h** [sergey-visual-studio/dpack#55]
I have a C++ Win64 project.
Some project files permanently "lose ability" to list its functions, some files not.

![Screenshot 2023-05-09 081818](https://user-images.githubusercontent.com/29715269/237025146-91c50607-6279-42d6-a3f3-54c0398d3b73.png)

I don't have steps to reproduce the issue. Restarting MSVS doesn't help. Reinstalling the extension doesn't help too.
Latest Microsoft Visual Studio Community 2022 (64-bit) 17.5.5
Latest extension version 4.5.3

Unfortunately I couldn't locate a DPack log file. Where should I look for it?
I can collect additional debug information or try some actions what could help to diagnose the issue, but I need guidance.

The extension is barely useful due to this issue.

**Comment by sergey-visual-studio** [comment]
That's a tough one to pinpoint not being to reproduce it and that being C++, which I rarely use, if ever. Feel free to reach out again if you come up with a repro case. Log file should be located under _<AppData>\Local\DPack Rx_.

My understanding that C++ VS code model is totally different from C#/VB. Additionally I'd love to convert C#/VB support to use Roslyn, which would then allow to browse any code file, whether it's part of the project or not. Unfortunately, there is no C++ Roslyn and thus I'm stuck on old unified code model API.

One thing I do recall from way back while implementing C++ support is that VS rebuilds C++ projects code model in the background. So it's possible to run into scenario where there is no code model shown. Perhaps you could see if removing project obj, .vs folders, or whatever C++ alternative is, and reloading the project helps.

**Comment by d-s-h** [comment]
I found a log file and a related error record:
`
16:15:36.319  *** Start logging ***
16:15:36.319  Initialization      Date: 5.17.23
16:15:36.319  Initialization      Version: 4.5.3.0
16:15:36.319  Initialization      Visual Studio: 17.5.33627.172 D17.5
16:15:36.319  Initialization      OS: 10.0.22621.0
16:15:36.319  Initialization      Process Id: 6304
16:15:36.324  Feature Factory     Loading FileBrowser feature
16:15:36.332  Feature Factory     Loaded FileBrowser feature
16:15:36.332  Feature Factory     Loading CodeBrowser feature
16:15:36.335  Feature Factory     Loaded CodeBrowser feature
16:15:36.335  Feature Factory     Loading SurroundWith feature
16:15:36.338  Feature Factory     Loaded SurroundWith feature
16:15:36.338  Feature Factory     Loading SupportOptions feature
16:15:36.346  Feature Factory     Loaded SupportOptions feature
16:15:36.346  Feature Factory     Loading Miscellaneous feature
16:15:36.348  Feature Factory     Loaded Miscellaneous feature
16:15:36.348  Feature Factory     Loading Bookmarks feature
16:15:36.350  Feature Factory     Loaded Bookmarks feature
16:15:36.358  Package             Preloaded select references
16:15:40.031  Bookmarks           Registered for bookmarks callback: main.cpp
16:15:40.031  Bookmark Tagger     File 'main.cpp' bookmark 0 change (Any)
16:15:44.707  Language            Cached 9 language definitions
16:15:44.709  Resolver            Check 'ebru' project language
16:15:44.711  Resolver            'ebru' project language is C++
16:15:44.711  File Processor      Collecting file code model: main.cpp
16:15:44.715  Resolver            'main.cpp' sub-type is Code
16:15:44.715  Shell               Collecting item code model: main.cpp
16:15:44.717  Shell               Collected item code model: main.cpp
16:15:44.725  Code Browser        Initializing...
16:15:44.728  File Processor      Collecting code members for 'main.cpp'
16:15:44.728  Resolver            Check 'ebru' project language
16:15:44.728  Resolver            'ebru' project language is C++
16:15:44.728  Shell               Collecting item code model: main.cpp
16:15:44.729  Shell               Collected item code model: main.cpp
16:15:44.731  File Processor      Error refreshing code model for 'main.cpp'
System.Runtime.InteropServices.COMException (0x80040065): Invalid DVTARGETDEVICE structure (Exception from HRESULT: 0x80040065 (DV_E_DVTARGETDEVICE))
   at EnvDTE.CodeElements.GetEnumerator()
   at DPackRx.CodeModel.FileProcessor.GetMembersInternal(Object projectItem, List`1 model, ProcessorFlags flags, CodeModelFilterFlags filter) in D:\a\1\s\DPackRx\CodeModel\FileProcessor.cs:line 257
16:15:44.736  Code Browser        Initialized
`

Indeed removing obj/.vs folders helped to fix the issue. At least for now. But I'm sure I'll face it again later. Will keep an eye to catch repro steps.

**Comment by sergey-visual-studio** [comment]
Never seen that error before tbhwy, but then again I don't work with C++. If there is something that ties your main.cpp and DVTARGETDEVICE, whatever that is, and it's reproducible please submit a test case for that and reopen this issue. Thanks.
