### ISSUE TITLE
The DPack dialog can not pop up in VS 2022

### ISSUE THREAD

**Issue by wangjiealice** [sergey-visual-studio/dpack#57]
"Alt" + "U" can not make the DPack dialog pop up in Microsoft Visual Studio Enterprise 2022 (64-bit)
Version 17.6.3

**Comment by wangjiealice** [comment]
Need to click Tools->DPack->Options->click "Keyboard shortcuts" to reset the default shortcuts.

**Comment by sergey-visual-studio** [comment]
Yeah, that "Keyboard shortcuts" should be one time thing. Did it start working for you after that?
