### ISSUE TITLE
App.config files don't open

### ISSUE THREAD

**Issue by igitur** [sergey-visual-studio/dpack#59]
1. File Browser -> selecting app.config and pressing enter doesn't open the file
2. Open a project with app.config, Alt+U to open File Browser. Select app.config. Press enter. 
8. Provide your development environment details:
  a. OS type and version `Windows 10 64b`
  b. Visual Studio version from Help|About: `17.7.4`
  c. DPack version from Help|About: `4.5.5`
  d. Project language you're working with. `C# SDK project type` (I think the SDK project type + app.config file combination might be relevant)
  e. Project type you're working with (Win, Web, .NET Core, etc). `Win`

Issue seems to be that https://github.com/sergey-visual-studio/dpack/blob/90ca6b0548e7544a14f6614cffba19fc6ffcccac/DPackRx/Services/ShellService.cs#L2403C13-L2403C13 throws an exception (`0x80041FEB`)

If https://github.com/sergey-visual-studio/dpack/blob/90ca6b0548e7544a14f6614cffba19fc6ffcccac/DPackRx/CodeModel/FileTypeResolver.cs#L159 returns `false` for the item (i.e. not treat app.config as a code subtype), then it opens correctly subsequently with `dteItem.Open(EnvDTE.Constants.vsViewKindPrimary);`.

**Comment by sergey-visual-studio** [comment]
Thanks for the detailed report. Reproduced. Patch doesn't look too bad. I'll take me some time to get to that though.

**Comment by igitur** [comment]
I could try a PR, but when it comes to the unit tests, I'm a bit lost. I have to test it, but I think for old school project files, the app.config is considered a code file, but for SDK style projects, it's not considered a code file. If that's the case, then I think the extension should clearly differentiate between these 2 kinds of projects and handle accordingly.

**Comment by sergey-visual-studio** [comment]
I'll get another beta out hopefully over the weekend for you. Thanks.

**Comment by sergey-visual-studio** [comment]
This should be fixed in newly posted release version. Re-open the issue if problem still persists.
